{
 "title": "nntp",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server Sessions",
   "type": "stat",
   "gridPos": { "h": 17, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nntplexer_server_sessions_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Article Requests (min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "increase(nntplexer_nntp_article_requests_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backend Requests by Code (min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "increase(nntplexer_nntp_backend_requests_total[$__rate_interval])",
     "legendFormat": "{{backend}} - {{code}}"
    }
   ]
  },
  {
   "title": "Server Requests (min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(nntplexer_server_requests_total[$__rate_interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Server Responses (min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "increase(nntplexer_server_responses_total[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Backend Response Rate (min)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(nntplexer_nntp_backend_bytes[$__rate_interval])",
     "legendFormat": "{{backend}}"
    }
   ]
  }
 ]
}